// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "pixel-icon": {
      name: "pixel-icon",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/pixel-icon.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/pixel-icon.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "book": {
      name: "book",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/book.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/book.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "vercel-grid": {
      name: "vercel-grid",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/vercel-grid.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/vercel-grid.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "pixel-icon-demo": {
      name: "pixel-icon-demo",
      type: "registry:example",
      registryDependencies: ["pixel-icon"],
      files: ["registry/default/example/pixel-icon-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/pixel-icon-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "vercel-grid-demo-text": {
      name: "vercel-grid-demo-text",
      type: "registry:example",
      registryDependencies: ["vercel-grid"],
      files: ["registry/default/example/vercel-grid-demo-text.tsx"],
      component: React.lazy(() => import("@/registry/default/example/vercel-grid-demo-text.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "book-demo": {
      name: "book-demo",
      type: "registry:example",
      registryDependencies: ["book"],
      files: ["registry/default/example/book-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/book-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "book-variant-demo": {
      name: "book-variant-demo",
      type: "registry:example",
      registryDependencies: ["book"],
      files: ["registry/default/example/book-variant-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/book-variant-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
