// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  "default": {
    "pixel-icon": {
      name: "pixel-icon",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/pixel-icon.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/pixel-icon.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "split-text-effect": {
      name: "split-text-effect",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/split-text-effect.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/split-text-effect.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "view-magnifier": {
      name: "view-magnifier",
      type: "registry:ui",
      registryDependencies: undefined,
      files: ["registry/default/bucharitesh/view-magnifier.tsx"],
      component: React.lazy(() => import("@/registry/default/bucharitesh/view-magnifier.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "pixel-icon-demo": {
      name: "pixel-icon-demo",
      type: "registry:example",
      registryDependencies: ["pixel-icon"],
      files: ["registry/default/example/pixel-icon-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/pixel-icon-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "split-text-effect-demo": {
      name: "split-text-effect-demo",
      type: "registry:example",
      registryDependencies: ["split-text-effect"],
      files: ["registry/default/example/split-text-effect-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "split-text-effect-demo-2": {
      name: "split-text-effect-demo-2",
      type: "registry:example",
      registryDependencies: ["split-text-effect"],
      files: ["registry/default/example/split-text-effect-demo-2.tsx"],
      component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo-2.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "split-text-effect-demo-3": {
      name: "split-text-effect-demo-3",
      type: "registry:example",
      registryDependencies: ["split-text-effect"],
      files: ["registry/default/example/split-text-effect-demo-3.tsx"],
      component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo-3.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "view-magnifier-demo": {
      name: "view-magnifier-demo",
      type: "registry:example",
      registryDependencies: ["view-magnifier"],
      files: ["registry/default/example/view-magnifier-demo.tsx"],
      component: React.lazy(() => import("@/registry/default/example/view-magnifier-demo.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "view-magnifier-demo-2": {
      name: "view-magnifier-demo-2",
      type: "registry:example",
      registryDependencies: ["view-magnifier"],
      files: ["registry/default/example/view-magnifier-demo-2.tsx"],
      component: React.lazy(() => import("@/registry/default/example/view-magnifier-demo-2.tsx")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
    "utils": {
      name: "utils",
      type: "registry:lib",
      registryDependencies: undefined,
      files: ["registry/default/lib/utils.ts"],
      component: React.lazy(() => import("@/registry/default/lib/utils.ts")),
      source: "",
      category: "undefined",
      subcategory: "undefined",
      chunks: []
    },
  },
}
