/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @typescript-eslint/no-explicit-any */
// @ts-nocheck
// This file is autogenerated by scripts/build-registry.ts
// Do not edit this file directly.

import React from "react";

export const Index: Record<string, any> = {
  "utils": {
    name: "utils",
    description: "",
    type: "registry:lib",
    files: [{
      path: "registry/default/lib/utils.ts",
      type: "registry:lib",
    }],
  },
  "book": {
    name: "book",
    description: "A book component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/book/book.tsx",
      type: "registry:component",
    },{
      path: "registry/default/bucharitesh/book/book.css",
      type: "registry:style",
    }],
  },
  "modern-progress": {
    name: "modern-progress",
    description: "A modern progress component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/modern-progress/modern-progress.tsx",
      type: "registry:component",
    },{
      path: "registry/default/bucharitesh/modern-progress/modern-progress.css",
      type: "registry:style",
    }],
  },
  "pixel-icon": {
    name: "pixel-icon",
    description: "A pixel icon component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/pixel-icon/pixel-icon.tsx",
      type: "registry:component",
    }],
  },
  "split-text-effect": {
    name: "split-text-effect",
    description: "A split text effect component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/split-text-effect/split-text-effect.tsx",
      type: "registry:component",
    }],
  },
  "view-magnifier": {
    name: "view-magnifier",
    description: "A view magnifier component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/view-magnifier/view-magnifier.tsx",
      type: "registry:component",
    }],
  },
  "game-of-life": {
    name: "game-of-life",
    description: "A game of life component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/game-of-life/game-of-life.tsx",
      type: "registry:component",
    }],
  },
  "magical-mouse": {
    name: "magical-mouse",
    description: "A magical mouse component for Next.js apps with next-themes and Tailwind CSS, supporting system, light, and dark modes.",
    type: "registry:component",
    files: [{
      path: "registry/default/bucharitesh/magical-mouse/magical-mouse.tsx",
      type: "registry:component",
    },{
      path: "registry/default/bucharitesh/magical-mouse/magical-mouse.css",
      type: "registry:style",
    }],
  },
  "book-demo": {
    name: "book-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/book-demo.tsx",
      type: "registry:component",
    }],
  },
  "book-variant-demo": {
    name: "book-variant-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/book-variant-demo.tsx",
      type: "registry:component",
    }],
  },
  "game-of-life-demo": {
    name: "game-of-life-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/game-of-life-demo.tsx",
      type: "registry:component",
    }],
  },
  "game-of-life-demo-2": {
    name: "game-of-life-demo-2",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/game-of-life-demo-2.tsx",
      type: "registry:component",
    }],
  },
  "magical-mouse-demo": {
    name: "magical-mouse-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/magical-mouse-demo.tsx",
      type: "registry:component",
    }],
  },
  "modern-progress-demo": {
    name: "modern-progress-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/modern-progress-demo.tsx",
      type: "registry:component",
    }],
  },
  "pixel-icon-demo": {
    name: "pixel-icon-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/pixel-icon-demo.tsx",
      type: "registry:component",
    }],
  },
  "split-text-effect-demo": {
    name: "split-text-effect-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/split-text-effect-demo.tsx",
      type: "registry:component",
    }],
  },
  "split-text-effect-demo-2": {
    name: "split-text-effect-demo-2",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/split-text-effect-demo-2.tsx",
      type: "registry:component",
    }],
  },
  "split-text-effect-demo-3": {
    name: "split-text-effect-demo-3",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/split-text-effect-demo-3.tsx",
      type: "registry:component",
    }],
  },
  "view-magnifier-demo": {
    name: "view-magnifier-demo",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/view-magnifier-demo.tsx",
      type: "registry:component",
    }],
  },
  "view-magnifier-demo-2": {
    name: "view-magnifier-demo-2",
    description: "",
    type: "registry:block",
    files: [{
      path: "registry/default/example/view-magnifier-demo-2.tsx",
      type: "registry:component",
    }],
  },
  "book-demo": {
    name: "book-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/book-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/book-demo.tsx")),
  },
  "book-variant-demo": {
    name: "book-variant-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/book-variant-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/book-variant-demo.tsx")),
  },
  "game-of-life-demo": {
    name: "game-of-life-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/game-of-life-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/game-of-life-demo.tsx")),
  },
  "game-of-life-demo-2": {
    name: "game-of-life-demo-2",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/game-of-life-demo-2.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/game-of-life-demo-2.tsx")),
  },
  "magical-mouse-demo": {
    name: "magical-mouse-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/magical-mouse-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/magical-mouse-demo.tsx")),
  },
  "modern-progress-demo": {
    name: "modern-progress-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/modern-progress-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/modern-progress-demo.tsx")),
  },
  "pixel-icon-demo": {
    name: "pixel-icon-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/pixel-icon-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/pixel-icon-demo.tsx")),
  },
  "split-text-effect-demo": {
    name: "split-text-effect-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/split-text-effect-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo.tsx")),
  },
  "split-text-effect-demo-2": {
    name: "split-text-effect-demo-2",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/split-text-effect-demo-2.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo-2.tsx")),
  },
  "split-text-effect-demo-3": {
    name: "split-text-effect-demo-3",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/split-text-effect-demo-3.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/split-text-effect-demo-3.tsx")),
  },
  "view-magnifier-demo": {
    name: "view-magnifier-demo",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/view-magnifier-demo.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/view-magnifier-demo.tsx")),
  },
  "view-magnifier-demo-2": {
    name: "view-magnifier-demo-2",
    description: "",
    type: "registry:example",
    files: [{
      path: "registry/default/example/view-magnifier-demo-2.tsx",
      type: "registry:component",
    }],
    component: React.lazy(() => import("@/registry/default/example/view-magnifier-demo-2.tsx")),
  },
}